### ISSUE TITLE
Can't save interactive videos (h5p-update-error)

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#1039]
Are there serious problems with macOS Big Sur known? Currently I cannot save interactive videos with Lumi. The GUI shows the error "h5p-update-error". The following entries are in the developer console:

```
sentry.io/api/1876151/store/?sentry_key=02e4da31636d479f86a17a6ef749278c&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
:52884/api/v1/lumi/package/undefined:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:52884/api/v1/lumi/:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

While testing I noticed the same problem happening at least with the course presentation type, but there it was not reproducible.

**Comment by sr258** [comment]
I don‘t have access to a Mac, so I‘m not sure if there might be incompatibilities. @JPSchellenberg can you test it?

**Comment by JPSchellenberg** [comment]
Sure.. I will test it and have a look at it.

**Comment by pheraph** [comment]
If there's anything I can do to help please let me know.

**Comment by sr258** [comment]
I've checked and the problem also exists on other OSes, so it's not specific to the new macOS. Looks like either a regression or a change in interactive video's behavior by H5P.

I've noticed that the problem only seems to occur if you don't enter a title for the video activity. Can you confirm this, @pheraph? My best guess is that it is caused by a validation error and the error message is misleading. I've recently introduced server-side text field validation to prevent XSS attack vectors. It is quite possible the server component now doesn't accept content without titles anymore as they don't conform to the schema.

**Comment by pheraph** [comment]
I can confirm that entering a title makes the content type saveable. In general I noticed that required fields aren't validated on saving or closing a modal dialog.

I still get some errors in the log:

```
Failed to load resource: the server responded with a status of 429 (Too Many Requests)
:58608/api/v1/lumi/package/undefined:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.js:2 Allow attribute will take precedence over 'allowfullscreen'.
attr @ jquery.js:2
:58608/api/v1/lumi/?contentId=1838853745:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
websocket.js:207 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ websocket.js:207
```

**Comment by sr258** [comment]
Alright, thanks for the confirmation! There should be an easy fix that simply prevents saving in the UI when no title was set. I will implement it this evening. H5P does not validate values entered into modals in general. The same behavior can be seen on h5p.org and other sites. This is something Joubel has to add. The only thing the offical h5p implementation validates is the title. (validation of content on the client is commented out in the source code)

You can ignore the first two errors, I think, they are not really much of a problem. We're working on a big refactoring of the frontend code, so I hope they will disappear soon. 

The last error is something I will look into, but it is probably not critical.

**Comment by pheraph** [comment]
Thanks for your reply, good to know there is a workaround available.

**Comment by sr258** [comment]
Just noticed: The issue is still there, as switching tabs from content without a title still causes the h5p-update-error.

**Comment by JPSchellenberg** [comment]
This will be resolved in the upcoming client overhaul as the view will be disabled until the h5p successfully validates.

**Comment by sr258** [comment]
you mean the complete UI view?

**Comment by JPSchellenberg** [comment]
No, I mean the preview tab will be disabled until the h5p successfully validates.
