### ISSUE TITLE
new Lumi doesn't start in windows

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#1112]
**Describe the bug**
Running `npm start` doesn't work:

Console output:
> DEBUG=* PORT=8080 NODE_ENV=development ./node_modules/.bin/electron .
20:11:00.850 > app is ready
(node:12012) UnhandledPromiseRejectionWarning: SyntaxError: C:\Users\seret\AppData\Roaming\lumi/config.json: Unexpected token (node:12012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that 

Possibly this has to do with the way the config.json file is referenced (unix path format).

**Comment by sr258** [comment]
It's not the way the paths are constructed. Maybe the file doesn't exist? @JPSchellenberg  How is the config.json file supposed to be copied to the user's data directory?

**Comment by JPSchellenberg** [comment]
The config.json file should be created during the boot-process if it doesn't exist:

https://github.com/Lumieducation/Lumi/blob/master/server/src/boot/setup.ts#L18

I don't know if it is the best solution to keep the config.json in the user-settings. My idea behind this was to make the content-hub-endpoint configurable.

**Comment by sr258** [comment]
The config should definitely be stored in the user settings. Ideally the uid sent to the h5p hub should be fetched dynamically from the hub at first startup and then saved. Currently we have a hardcoded uid, which is not ideal.
