### ISSUE TITLE
Save buttons

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#1122]
- The state of the save buttons should revert to the default some time after the success / error state.
- It would also be good to have a tooltip, as it's unclear what they do.
- The export HTML option should also (only?) be accessible from the "File" menu
- The save icon could be replaced by a more modern symbol (the disk analogy is probably too old by now)

**Comment by JPSchellenberg** [comment]
The question is if we keep the html-buttons or we allow only the menu-items & keyboard shortcuts like every other application. What do you think?

**Comment by JPSchellenberg** [comment]
As far as I remember I added the html save button as I thought the software might also run on a webserver. But now it is only designed for the use within electron, so we might get rid of that button to make more space for the editor and be more consistent with other apps.

**Comment by sr258** [comment]
I would remove the save buttons in general, as they are more mobile app style and not so much typical for a desktop app.

**Comment by JPSchellenberg** [comment]
This was resolved in #1134
