### ISSUE TITLE
Pacman build broken in new Lumi

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#1128]
Just after the PR with the pacman build was merged, we also merged a big refactoring of the GUI. Now the pacman build process doesn't work anymore. I've removed it from the CI pipeline temporarily. @benabel do you have an idea what might be the cause?

Logs with not very helpful error message can be found here: https://github.com/Lumieducation/Lumi/runs/1651080328

**Comment by benabel** [comment]
This seems to be due to to missing bdstar command. I've commented on the pr. If you want I'll add the Pac-Man build after the ci pr is merged.
