### ISSUE TITLE
Presumably missing call to validate parameters

### ISSUE THREAD

**Issue by otacke** [Lumieducation/Lumi#1150]
**Describe the bug**
Parameters can get lost when exporting content.

The editor of H5P needs to validate parameter fields in order to get them into the actual parameter set. For non-CKEditor fields like regular text fields, this is not done unless you tab into another field or save the content (or in Lumi's case switch to the view). Thus, if you don't preview your content but export it right away, the last parameter may get lost.

I assume that validating the form before calling the export function will fix this problem.

**Environment (please complete the following information):**
 - OS: Linux, but should not matter
 - Browser: Electron, so I guess some form of Blink/Chromium :-)
 - Nodejs-Version [whatever Lumi brings along]

**To Reproduce**
1. Go to the H5P Editor Hub
2. Create content that contains a simple text field (e.g. Multiple Choice Question or Chart)
3. Fill out the form, but fill out a simple text field last (e.g. the feedback in the overall feedback of Multiple Choice or the Label field of Chart) and don't tab into another field or view the result before exporting to an HTML file.
4. Open the HTML file in a browser: the parameter content of the simple text field is missing.

**Expected behavior**
All parameters are saved.

**Comment by sr258** [comment]
Thanks for the report! We do run the validation, but the current text field needs to be blurred for this to work.

**Comment by otacke** [comment]
@sr258 Ah, it was the change listener, not the validation. Sorry, have not worked with the editor in ages, just had a faint memory of running across that issue once.
