### ISSUE TITLE
Library management

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#1159]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to upload custom libraries into Lumi. 

**Describe the solution you'd like**
We could provide a graphical user interface to the already existing library-admin interface of the h5p-nodejs-library.

**Comment by sr258** [comment]
Why not? You can simply open an arbitrary H5P file with a new library.

**Comment by sr258** [comment]
We still need the management page, though, to allow users to delete old libraries. As uploading "unusual" libraries is also a bit of a security risk, the management page would definitely be a good thing. It would also be good to get a warning if you upload content with a library that's not on the hub.

**Comment by JPSchellenberg** [comment]
I received an email with this request. The user wanted to install https://www.olivertacke.de/labs/wp-content/uploads/2020/08/H5P.ARScavenger-library.h5p .
If you want to use this, you can not simply import it, because the variation fails due to a missing content.json and h5p.json. So an install via a library-management page would be good.

**Comment by sr258** [comment]
Included in 0.7.1
