### ISSUE TITLE
Lumi should open when clicking on .h5p files

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#1169]
**Is your feature request related to a problem? Please describe.**
The Lumi App should be started when clicking on a .h5p file and open that .h5p file. If Lumi is already running the .h5p file should be opened.

It should be doable with https://www.electronjs.org/docs/all#event-open-file-macos 
It also states: 
> On Windows, you have to parse process.argv (in the main process) to get the filepath.

**Comment by sr258** [comment]
The exe installer for Windows will only allow this if the application is installed system-wide (requires admin privileges and a different build flag when we build the package). The Windows Store version should be able to handle this. Not sure where you can configure it, though.

**Comment by sr258** [comment]
I could do a first draft of this.
