### ISSUE TITLE
"Missing translation of library core" flashes when opening editor

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#117]
"Missing translation of library core" flashes when opening editor. The reason is that the order of the JS includes is not correct. This might be fixed by a newer version of the h5p-nodejs-library.

**Comment by sr258** [comment]
When investigating this, I found that the order of the js references is hard-coded in src/client/public/index.html along with the H5PIntegration object. This is something the renderer would normally generate. @JPSchellenberg  Is there any reason that all of this is hardcoded and not dynamically generated?

**Comment by JPSchellenberg** [comment]
No, the reason was to get the Editor running as fast as possible and I think this was one way and I forgot about it. We should definitely change that.

**Comment by sr258** [comment]
Alright, I don't think making this dynamic is a top priority right now - there are many more pressing things, but we should keep this in mind.
