### ISSUE TITLE
Overwrite file warning

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#1172]
If you select an existing file in the save or export dialog, it is simply overriden. The user should be offered a choice whether they really want to overwrite it.

**Comment by JPSchellenberg** [comment]
On which OS have you experienced this? on macOS it asks for a overwrite confirmation. On Linux that should be no problem as electron offers the corresponding setting: https://www.electronjs.org/docs/all#dialogshowsavedialogsyncbrowserwindow-options

If it is on windows we would have to add a custom dialog and not the system dialog.
