### ISSUE TITLE
Missing translation in CoursePresentation

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#1228]
Someone on twitter mentioned that course presentation is missing a translation. I am not sure if it is a problem on our side or the h5p editor core. 

**Screenshots**
![Screenshot 2021-02-05 at 22 35 51](https://user-images.githubusercontent.com/9697985/107091720-81b0c100-6802-11eb-9a94-5d40bf00bcb5.png)

![Screenshot 2021-02-05 at 22 36 36](https://user-images.githubusercontent.com/9697985/107091786-9c833580-6802-11eb-9558-7a40de058d74.png)

**Comment by sr258** [comment]
This is a bug in h5p-server. It should return the English default language file if the localized one doesn't exist. The problem is that we don't save the .en language file at the moment, so it's not installed in all existing clients. We'll have to think about this one...

**Comment by sr258** [comment]
I've found a fix in h5p-sever that's easy enough. We cannot merge it until the new monorepo is in the main branch.

**Comment by JPSchellenberg** [comment]
The new monorepo is in the main branch now.

**Comment by JPSchellenberg** [comment]
This should be fixed in v0.5.1
