### ISSUE TITLE
Clicking on "edit" lots of times breaks viewer

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#125]
**Describe the bug**
Clicking on "edit" lots of times breaks viewer

**Environment (please complete the following information):**
- v0.0.7

**To Reproduce**
1. Open app
2. Load file
3. Click on edit
4. Click on edit 20x very fast
5. Click on view --> nothing happens

**Comment by JPSchellenberg** [comment]
I think this really depends on the speed of the machine. On my MacBook I can not reproduce this error as the request is finished in less than 50 ms.

**Comment by sr258** [comment]
Still, cancelling old requests might be a good idea.
