### ISSUE TITLE
Make library-storage path configurable

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#1283]
**Is your feature request related to a problem? Please describe.**
On school networks it makes sense to store the libraries in a shared folder rather than the user folder.

**Describe the solution you'd like**
The library post could be configurable.

**Comment by sr258** [comment]
I'm interested in the exact use case of this request. This would make Lumi a multi-user system and introduce some complexity that the desktop app luckily doesn't have. While it might be easy to simply allow changing the library path (would also enable interesting use cases like H5P library development), there might be stability and security issues.

**Comment by sr258** [comment]
Since 0.7.1 there's a `--libs=...` command line option to change the library path.
