### ISSUE TITLE
Add a dev mode

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1305]
I am trying to create a new content type for h5p (still new at that). I am not talking about creating activity with h5p, but creating a new content type.

Lumni is really nice, because I am able to do it without having to install h5p on a drupal for exemple.
I just create a basic h5p content and opened it in lumi. I then went where lumi store its content and I can directly edit my files.

However, I have to restart lumi after each modification to make my update avaible.

I tried to open the dev tool and disabled cache, but the nodejs server produce error (ERR_CONTENT_LENGTH_MISSMATCH) when trying to load updated file.
Maybe it's because the nodejs try to cache the content but detect a change ? If this is that, it would be nice to have a way (even an obscure way) to disable cache on the nodejs server in order to be able to use lumi easily to dev content ?

**Comment by sr258** [comment]
There is a server-side cache that caches library metadata to reduce loading times. You’re probably having issues with it. It might be an option to disable it with a command line flag or environment variable. I‘ll look into it.

**Comment by sr258** [comment]
@DegrangeM We've implemented a basic library development mode:

You can start Lumi with the `--dev` and `--libs=<YOUR_LIBRARY_PATH>`. `--dev` disables the library cache and `--libs=` allows setting custom paths to the library directory, so that you can set it to your dev folder.

I've still noticed some issues if you have development artifacts in a library directory (e.g. massive node_module directories). It's advisable to only copy over the files that are really needed by H5P and to develop in a different directory. I use `rsync` with `--exlude-from=.h5pignore` to copy over files.

We're welcoming feedback on the dev mode, as I'm currently not doing any library development for H5P.

**Comment by DegrangeM** [comment]
Thanks.

I recently found a software very close to lumi (logiquiz, free but not opensource) that didn't cache library so I started developping my future Python content type with it (even if it was a little tricky at first). I will continue my dev with logiquiz for this was but I will test Lumi for my next content type and tell you if everythings work good.

**Comment by sr258** [comment]
Can you post a link to logiquiz? I've never heard of it before and I'd be interested in checking it out.

**Comment by sr258** [comment]
Never mind, found it! It's even open source: https://gitlab.com/ladigitale/logiquiz (and it must be, as it's based on our h5p-nodejs-library ;) ). I wonder why those guys decided to do their own thing instead of just working on Lumi, though...

**Comment by DegrangeM** [comment]
Wow, that's nice they are open source. I missed that !

Well there is some difference between the two software. The big one is that they store created h5p and you can view / edit them easily without having to reopen the h5p file like for lumi. But they could have added that to lumi :D 

Maybe they plan to integrate logiquiz with digiquiz later (that allow to upload .h5P online) and for this reason needed to create they own tool. (but the old privacy policiy webpage of lumi let me think that you will also propose a service like that called lumi.run).

**Comment by sr258** [comment]
Yes, Lumi Run is in the making. We do have a working draft for it. It's mostly a matter of sorting out all legal requirements.

**Comment by DegrangeM** [comment]
It work great (but you need to disable cache with console dev) Thanks ! Logiquizz is more pratical because it keep h5p file and you don't have to reopen it each time, but lumi is better because it allow to manage library.

**Comment by DegrangeM** [comment]
Hum, the cache is not always updated, I am investingating this issue.
