### ISSUE TITLE
.lumi report file with no xapi prevent analysing everything

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1312]
**Describe the bug**
I am currently developing a new content type. I just added xapi support.
I exported my content to html, did the activity and generated the .lumi file and opened it in the analyser
It worked perfectly.
Then I reopened my content but this time generated the .lumi file without doing anything on the activity.
I then tried to analyse my two previous .lumi file but got the message "No valid data found" and nothing showed on the analytic panel.

**Environment (please complete the following information):**
 - OS: windows 10
 - Lumi Version 5.1.0

**Expected behavior**
I was expecting the report to at least show my first lumi, or both to at least get the username while showing no data for the second.

**Additional context**
I tried reproducing this with other content but wasn't able to do it because they generate xapi data even if the user do nothing. I don't know  if there is other content that does not produce xapi data when the user do nothing. Can provide my content file if you need it.

[test.lumi.txt](https://github.com/Lumieducation/Lumi/files/6134955/test.lumi.txt)

**Comment by sr258** [comment]
I'll check this out on the weekend. Your content type should probably always emit a xAPI `attempted` statement on load, though.

**Comment by DegrangeM** [comment]
Yes, this bug allowed me to think about adding it and it now does :p

**Comment by sr258** [comment]
@DegrangeM We've released 0.7.1 today, which includes improvements in the Analytics importer. Could you please check whether this issue persists?

**Comment by DegrangeM** [comment]
> @DegrangeM We've released 0.7.1 today, which includes improvements in the Analytics importer. Could you please check whether this issue persists?

I don't know how microsoft store work but is this normal that my lumi doesn't update ?

**Comment by DegrangeM** [comment]
Just got a notification about the update after closing lumi. However the update failed ("error launching installer").

It might be my fault (I tried to change permission of lumi file in order to try (unsuccessfully) the dev flag).  I will reinstall the apps but wanted to let you know it case it's not linked to my changes.

edit : still the error after reinstalling

**Comment by DegrangeM** [comment]
I confirm this issue is fixed ! 👍
