### ISSUE TITLE
Lumi Analytics: Cannot import *.lumi file

### ISSUE THREAD

**Issue by HerbHER** [Lumieducation/Lumi#1368]
Hi all,

after opening Lumi-Analytics and pressing the import button (".Lumi Dateien importieren" in german) a window opens in which you should choose the file.
In this window I only can select the folders that are shown in the left panel (i.e. recent, home, desktop, ...).
I cannot select any other folders, they are all grayed out.
Even with a right click it is not possible (see screenshot).

![screenshot](https://user-images.githubusercontent.com/81318437/112348209-e7301280-8cc7-11eb-8a8e-1254d352467e.png)

Also if I select any of the folders in the left panel it is not possible for me to import a .lumis file.

 - OS: ubuntu 18.04
 - Lumi Version: 0.5.3 2021-03-17 (169)

1. Go to 'Lumi-Analytics'
2. Click on 'import'
3. Try to switch to a folder other than in the left panel
4. not possible

Selecting of any folder should be possible. Import should be possible.

**Comment by sr258** [comment]
Thank you for reporting this! We already have an idea how to fix this!
