### ISSUE TITLE
no valid data found

### ISSUE THREAD

**Issue by Stephlabaraque** [Lumieducation/Lumi#1425]
**Describe the bug**
no valide data found in analytics

**Environment (please complete the following information):**
 - OS: Linux Mint
 - Lumi Version 0.6.1

**To Reproduce**
1. Go to 'Analytics"
2. Click on 'Choose a directory'
3.. See error

**Screenshots**
![Capture d’écran du 2021-04-07 19-08-11](https://user-images.githubusercontent.com/13810530/113906910-0b661600-97d5-11eb-8f27-c64100182809.png)

**Comment by sr258** [comment]
@Stephlabaraque We've release 0.7.1 today, which includes improvements in how the Analytics Tools find files. Could you please check whether this issue persists with 0.7.1?

**Comment by Stephlabaraque** [comment]
Perfect! Many thanks!
