### ISSUE TITLE
"error launching installer" when the apps try to update

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1461]
**Describe the bug**
Got a popup telling me an update was avaible when closing lumi. When I restart lumi i got an "error launching installer" popup error.

**Environment (please complete the following information):**
 - Windows 10
 - 6.1.0

**Additional context**
This might be not lumi fault as I tried to change permission / owner of some folder related to windows apps in order to try unsuccessfully to pass param to the windows apps (after searching on internet, you can't). However I uninstalled then reinstalled lumi and the issue is still here.

**Comment by sr258** [comment]
Did you install it through the Windows Store or with the exe installer?

**Comment by DegrangeM** [comment]
> Windows Store

 Windows Store

**Comment by sr258** [comment]
The Windows Store version has to pass a certification process by Microsoft before it is rolled out and 0.7.1 is currently in certification and not live yet. The .exe version auto-updates fine on my machine. Just tested it.

You also shouldn't see any update message in the Windows Store version at all, as updates are handled by the OS and not the application itself. 

As you said, I assume that Windows is unhappy about changing permissions of the folders. I can't really help here, but I think the best way might be to either use some restore point to restore to a working state of Windows in which the folder was unmodified. It might also help to execute a Windows Store repair. I've had issues with the store before, and there are command line commands (I think the program is wsstore.exe or something like that) to repair the store. This might help as well.

The easiest way might be to switch to the .exe installer, especially if you need to pass arguments to the program. It should not be affected.

**Comment by DegrangeM** [comment]
> You also shouldn't see any update message in the Windows Store version at all, as updates are handled by the OS and not the application itself.

Then that's the issue. I do get a message about update with the store version:

![image](https://user-images.githubusercontent.com/53106394/115148715-205a6900-a061-11eb-9307-7366415a1499.png)

**Comment by JPSchellenberg** [comment]
I will remove the updater from targets that update otherwise (MS Store, Mac App Store, etc) in the next release.

**Comment by sr258** [comment]
> I will remove the updater from targets that update otherwise (MS Store, Mac App Store, etc) in the next release.

Great, see https://stackoverflow.com/questions/66974771/see-build-target-of-electron-builder-in-running-application/66981283?noredirect=1#comment118445360_66981283 for how to do this in Linux. Auto-updates should only be enabled for AppImage builds on Linux. But I don't think the updater is active in these platforms...

**Comment by sr258** [comment]
> > You also shouldn't see any update message in the Windows Store version at all, as updates are handled by the OS and not the application itself.
> 
> Then that's the issue. I do get a message about update with the store version:
> 
> ![image](https://user-images.githubusercontent.com/53106394/115148715-205a6900-a061-11eb-9307-7366415a1499.png)

Can you disable the auto-update in the settings? Maybe this helps. You can also change this manually in %AppData%\Roaming\lumi\settings.json

**Comment by DegrangeM** [comment]
> > > You also shouldn't see any update message in the Windows Store version at all, as updates are handled by the OS and not the application itself.
> > 
> > 
> > Then that's the issue. I do get a message about update with the store version:
> > ![image](https://user-images.githubusercontent.com/53106394/115148715-205a6900-a061-11eb-9307-7366415a1499.png)
> 
> Can you disable the auto-update in the settings? Maybe this helps. You can also change this manually in %AppData%\Roaming\lumi\settings.json

This does work (after a restart, it still tell about update the first time you close the app after disabling auto update). This setting should probably be hidden and set to false when from windows store.

**Comment by sr258** [comment]
Yes, you're right. I can reproduce the issue here as well. The Windows Store version triggers the auto-update which installs a second installation using the exe installer. While it doesn't break things, there's a second installation and Lumi exists twice... Not great. This is a high priority issue.

**Comment by JPSchellenberg** [comment]
Should be fixed in the last release.
