### ISSUE TITLE
Customization options in HTML export

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#1475]
Users request options when exporting to HTML to make some content types work. Content types with very large width (see #343) might not work at all, if they are displayed full screen.

Possible options that make sense are:
- max-width
- max-height
- margin (absolute)
- vertical and horizontal alignment

It would also be good to be able to add custom css files to style exports (see #656).

**Comment by lsencabaugh** [comment]
It looks like this might be closable.

#2032

**Comment by sr258** [comment]
@lsencabaugh You're right. Thanks for the reminder!
