### ISSUE TITLE
Library can't be deleted - wrong error message

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1480]
The error message say it can't be deleted because there is 0 other library that use it.

![image](https://user-images.githubusercontent.com/53106394/115972325-f7990e80-a54d-11eb-8914-d8506bb6fec3.png)

It's illogical, but it's not the reason (I assume) that prevent it to be deletable, I assume it's the fact that there is 1 object created with this library.

![image](https://user-images.githubusercontent.com/53106394/115972338-0aabde80-a54e-11eb-904f-0e610e8dc97c.png)

Version 0.7.2.0

**Comment by DegrangeM** [comment]
As lumi doesn't save h5p file, that means that if you once do an h5p file with a library you can never delete it ?

**Comment by sr258** [comment]
You're right. Lumi doesn't clean up temporary files properly in some situation, which leads to this situation. We already have an issue for this: #1136

**Comment by sr258** [comment]
Fixed in 0.8.1.
