### ISSUE TITLE
Scorm package - load script/style on the fly ?

### ISSUE THREAD

**Issue by DegrangeM** [Lumieducation/Lumi#1483]
Hi,

The good things of lumi is that I can export the content-type I am creating to html / scorm if it end-up not being accepted by h5p or if my library doesn't get added to the h5p of the moodle of my school.

However I discovered that it currently doesn't work because my content-type load some javascript / css file on the fly (by adding script / link tag) and not by preloadJs/css attribute of the library.json file (to avoid loading all file because there are a lot and they are not all used at the same time).

I really don't know how scorm package work. Do you think there might be some trick to allow this to work in scorm package (or html export) ?

I am just asking because you might have some idea as you know how scorm things work, don't loose to much time by thinking about that, in the end if I really need it I can add all the js/css file to the preloadJs/css attribute.

Thanks

**Comment by sr258** [comment]
It's not the SCORM package but the way Lumi bundles all library files into the single HTML file. (the SCORM package is actually the HTML bundle with external resources plus a wrapper for SCORM): The HTML exporter inlines all scripts and styles into <script> and <style> tags. The library files are not included as separate files.

However, you should be able to use your dynamically loaded scripts if you get their URL with `H5P.ContentType.getLibraryFilePath` when loading them. The HTML bundler detects library files that weren't included in the bundle, adds them as base64 strings and overrides `H5P.ContentType.getLibraryFilePath` so that it loads the base64 encoded files.

The benefits of lazy loading are gone, however, as the HTML bundle must always be fully loaded anyway.

It would be possible to change how the SCORM export works and to include library files that are not preloaded in another way for this use case.

**Comment by DegrangeM** [comment]
Thanks, I was using `H5P.getLibraryPath` but I will see to use `H5P.ContentType.getLibraryFilePath` instead.

**Comment by DegrangeM** [comment]
Unfortunatly the library that load file on the fly isn't a standalone content-type. This means I can't have access to H5P.ContentType.getLibraryFilePath :(

edit : might work with something like `H5P.ContentType().prototype.getLibraryFilePath.call({libraryInfo:{versionedNameNoSpaces:'toto'}},'toto')`. I will try.

**Comment by DegrangeM** [comment]
I tried but it doesn't work.

I inspected `H5P.ContentType().prototype.getLibraryFilePath` on the exported html file and it return me the original function, not the one injected by lumi. Am I missing something ? thanks

![image](https://user-images.githubusercontent.com/53106394/116402637-f48f6e00-a82c-11eb-8d92-e35cefa0c6fe.png)

**Comment by sr258** [comment]
I guess it would not be a problem to also override `H5P.getLibraryFilePath` in addition to the one of `H5P.ContentType`. Can you provide a .h5p package that I can try it with?

**Comment by DegrangeM** [comment]
here the h5p file (remove .txt)

[lumiexportonthefly.h5p.txt](https://github.com/Lumieducation/Lumi/files/6394463/lumiexportonthefly.h5p.txt)

If it work the text red and green should be colored when exported.

The line that call getLibraryFilePath : https://github.com/DegrangeM/H5P-CodeMirror/blob/master/codemirror.js#L9

Thanks

**Comment by sr258** [comment]
I've identified the source of the problem: Your way of using `H5P.ContentType.getLibraryFilePath` is actually fine. The problem is that the html exporter only includes media resource files (cp. https://github.com/lumieducation/h5p-nodejs-library/blob/d08a7e86ffee03870e5063bbe204c789fb97e4e9/packages/h5p-html-exporter/src/HtmlExporter.ts#L514). As you lazy load JavaScript, the files aren't included and the override is not added to the bundle.

I've tried disabling the mimetype check and then your content type works fine. I'm not exactly sure by how much bundles will grow in general if I remove the mimetype check from the exporter. I'll have to test this with some more content types to see what unused files there are. 

Maybe I could also extend the mimetypes the bundler accepts: What extensions do you need?

Another solution might be to use a directory name convention that makes the bundler include all files in the directory regardless of the mimetype. This would be non-breaking to all other H5P implementations (as they don't care about the directory names inside libraries), but Lumi (and other h5p-nodejs-library implementations) would include the whole directory in HTML bundles...

**EDIT:**
Another way of doing this would be to extend the JSON schema of `library.json` to include a list of directories or files that should always be included in the bundler. While this would definitely work completely fine for lime, I'm not 100% certain if the original PHP implementation doesn't throw some validation errors if we do this. It's also not guaranteed that this won't happen in the future, even if the validation errors don't occur at the moment. That's why I'd still prefer the convention.

**Comment by DegrangeM** [comment]
I think you could add all files ending with `.js` and `.css`. Maybe `.json` but I don't use them.

I don't think there is many useless javascript and css file in h5p.

**Comment by sr258** [comment]
I've created a script to get a list of files that aren't included. Here are its outputs: 

```txt
EmbeddedJS-1.0/js/ejs.js
H5P.BranchingScenario-1.2/scripts/branchingScenario.js
H5P.BranchingScenario-1.2/scripts/genericScreen.js
H5P.BranchingScenario-1.2/scripts/libraryScreen.js
H5P.BranchingScenario-1.2/scripts/scoring.js
H5P.CKEditor-1.0/ckeditor/build-config.js
H5P.CKEditor-1.0/ckeditor/ckeditor.js
H5P.CKEditor-1.0/ckeditor/contents.css
H5P.CKEditor-1.0/ckeditor/lang/af.js
H5P.CKEditor-1.0/ckeditor/lang/ar.js
H5P.CKEditor-1.0/ckeditor/lang/az.js
H5P.CKEditor-1.0/ckeditor/lang/bg.js
H5P.CKEditor-1.0/ckeditor/lang/bn.js
H5P.CKEditor-1.0/ckeditor/lang/bs.js
H5P.CKEditor-1.0/ckeditor/lang/ca.js
H5P.CKEditor-1.0/ckeditor/lang/cs.js
H5P.CKEditor-1.0/ckeditor/lang/cy.js
H5P.CKEditor-1.0/ckeditor/lang/da.js
H5P.CKEditor-1.0/ckeditor/lang/de-ch.js
H5P.CKEditor-1.0/ckeditor/lang/de.js
H5P.CKEditor-1.0/ckeditor/lang/el.js
H5P.CKEditor-1.0/ckeditor/lang/en-au.js
H5P.CKEditor-1.0/ckeditor/lang/en-ca.js
H5P.CKEditor-1.0/ckeditor/lang/en-gb.js
H5P.CKEditor-1.0/ckeditor/lang/en.js
H5P.CKEditor-1.0/ckeditor/lang/eo.js
H5P.CKEditor-1.0/ckeditor/lang/es-mx.js
H5P.CKEditor-1.0/ckeditor/lang/es.js
H5P.CKEditor-1.0/ckeditor/lang/et.js
H5P.CKEditor-1.0/ckeditor/lang/eu.js
H5P.CKEditor-1.0/ckeditor/lang/fa.js
H5P.CKEditor-1.0/ckeditor/lang/fi.js
H5P.CKEditor-1.0/ckeditor/lang/fo.js
H5P.CKEditor-1.0/ckeditor/lang/fr-ca.js
H5P.CKEditor-1.0/ckeditor/lang/fr.js
H5P.CKEditor-1.0/ckeditor/lang/gl.js
H5P.CKEditor-1.0/ckeditor/lang/gu.js
H5P.CKEditor-1.0/ckeditor/lang/he.js
H5P.CKEditor-1.0/ckeditor/lang/hi.js
H5P.CKEditor-1.0/ckeditor/lang/hr.js
H5P.CKEditor-1.0/ckeditor/lang/hu.js
H5P.CKEditor-1.0/ckeditor/lang/id.js
H5P.CKEditor-1.0/ckeditor/lang/is.js
H5P.CKEditor-1.0/ckeditor/lang/it.js
H5P.CKEditor-1.0/ckeditor/lang/ja.js
H5P.CKEditor-1.0/ckeditor/lang/ka.js
H5P.CKEditor-1.0/ckeditor/lang/km.js
H5P.CKEditor-1.0/ckeditor/lang/ko.js
H5P.CKEditor-1.0/ckeditor/lang/ku.js
H5P.CKEditor-1.0/ckeditor/lang/lt.js
H5P.CKEditor-1.0/ckeditor/lang/lv.js
H5P.CKEditor-1.0/ckeditor/lang/mk.js
H5P.CKEditor-1.0/ckeditor/lang/mn.js
H5P.CKEditor-1.0/ckeditor/lang/ms.js
H5P.CKEditor-1.0/ckeditor/lang/nb.js
H5P.CKEditor-1.0/ckeditor/lang/nl.js
H5P.CKEditor-1.0/ckeditor/lang/no.js
H5P.CKEditor-1.0/ckeditor/lang/oc.js
H5P.CKEditor-1.0/ckeditor/lang/pl.js
H5P.CKEditor-1.0/ckeditor/lang/pt-br.js
H5P.CKEditor-1.0/ckeditor/lang/pt.js
H5P.CKEditor-1.0/ckeditor/lang/ro.js
H5P.CKEditor-1.0/ckeditor/lang/ru.js
H5P.CKEditor-1.0/ckeditor/lang/si.js
H5P.CKEditor-1.0/ckeditor/lang/sk.js
H5P.CKEditor-1.0/ckeditor/lang/sl.js
H5P.CKEditor-1.0/ckeditor/lang/sq.js
H5P.CKEditor-1.0/ckeditor/lang/sr-latn.js
H5P.CKEditor-1.0/ckeditor/lang/sr.js
H5P.CKEditor-1.0/ckeditor/lang/sv.js
H5P.CKEditor-1.0/ckeditor/lang/th.js
H5P.CKEditor-1.0/ckeditor/lang/tr.js
H5P.CKEditor-1.0/ckeditor/lang/tt.js
H5P.CKEditor-1.0/ckeditor/lang/ug.js
H5P.CKEditor-1.0/ckeditor/lang/uk.js
H5P.CKEditor-1.0/ckeditor/lang/vi.js
H5P.CKEditor-1.0/ckeditor/lang/zh-cn.js
H5P.CKEditor-1.0/ckeditor/lang/zh.js
H5P.CKEditor-1.0/ckeditor/plugins/link/dialogs/anchor.js
H5P.CKEditor-1.0/ckeditor/plugins/link/dialogs/link.js
H5P.CKEditor-1.0/ckeditor/plugins/table/dialogs/table.js
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/dialog_ie.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/dialog_ie8.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/dialog_iequirks.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/dialog.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/editor_gecko.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/editor_ie.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/editor_ie8.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/editor_iequirks.css
H5P.CKEditor-1.0/ckeditor/skins/moono-lisa/editor.css
H5P.CKEditor-1.0/ckeditor/styles.js
Odometer-1.0/themes/odometer-theme-car.css
Odometer-1.0/themes/odometer-theme-digital.css
Odometer-1.0/themes/odometer-theme-minimal.css
Odometer-1.0/themes/odometer-theme-plaza.css
Odometer-1.0/themes/odometer-theme-slot-machine.css
Odometer-1.0/themes/odometer-theme-train-station.css
TimelineJS-1.1/css/themes/dark.css
TimelineJS-1.1/css/themes/font/AbrilFatface-Average.css
TimelineJS-1.1/css/themes/font/Arvo-PTSans.css
TimelineJS-1.1/css/themes/font/Bevan-PotanoSans.css
TimelineJS-1.1/css/themes/font/BreeSerif-OpenSans.css
TimelineJS-1.1/css/themes/font/DroidSerif-DroidSans.css
TimelineJS-1.1/css/themes/font/Georgia-Helvetica.css
TimelineJS-1.1/css/themes/font/Lekton-Molengo.css
TimelineJS-1.1/css/themes/font/Lora-Istok.css
TimelineJS-1.1/css/themes/font/Merriweather-NewsCycle.css
TimelineJS-1.1/css/themes/font/NewsCycle-Merriweather.css
TimelineJS-1.1/css/themes/font/NixieOne-Ledger.css
TimelineJS-1.1/css/themes/font/Pacifico-Arimo.css
TimelineJS-1.1/css/themes/font/PlayfairDisplay-Muli.css
TimelineJS-1.1/css/themes/font/PoiretOne-Molengo.css
TimelineJS-1.1/css/themes/font/PT.css
TimelineJS-1.1/css/themes/font/PTSerif-PTSans.css
TimelineJS-1.1/css/themes/font/Rancho-Gudea.css
TimelineJS-1.1/css/themes/font/SansitaOne-Kameron.css
TimelineJS-1.1/css/timeline.css
TimelineJS-1.1/js/locale/af.js
TimelineJS-1.1/js/locale/ar.js
TimelineJS-1.1/js/locale/bg.js
TimelineJS-1.1/js/locale/ca.js
TimelineJS-1.1/js/locale/cz.js
TimelineJS-1.1/js/locale/da.js
TimelineJS-1.1/js/locale/de.js
TimelineJS-1.1/js/locale/el.js
TimelineJS-1.1/js/locale/en-24hr.js
TimelineJS-1.1/js/locale/en-week.js
TimelineJS-1.1/js/locale/en.js
TimelineJS-1.1/js/locale/eo.js
TimelineJS-1.1/js/locale/es.js
TimelineJS-1.1/js/locale/et.js
TimelineJS-1.1/js/locale/eu.js
TimelineJS-1.1/js/locale/fa.js
TimelineJS-1.1/js/locale/fi.js
TimelineJS-1.1/js/locale/fo.js
TimelineJS-1.1/js/locale/fr.js
TimelineJS-1.1/js/locale/gl.js
TimelineJS-1.1/js/locale/he.js
TimelineJS-1.1/js/locale/hr.js
TimelineJS-1.1/js/locale/hu.js
TimelineJS-1.1/js/locale/hy.js
TimelineJS-1.1/js/locale/id.js
TimelineJS-1.1/js/locale/is.js
TimelineJS-1.1/js/locale/it.js
TimelineJS-1.1/js/locale/iw.js
TimelineJS-1.1/js/locale/ja.js
TimelineJS-1.1/js/locale/ka.js
TimelineJS-1.1/js/locale/ko.js
TimelineJS-1.1/js/locale/lb.js
TimelineJS-1.1/js/locale/lt.js
TimelineJS-1.1/js/locale/lv.js
TimelineJS-1.1/js/locale/ms.js
TimelineJS-1.1/js/locale/ne.js
TimelineJS-1.1/js/locale/nl.js
TimelineJS-1.1/js/locale/no.js
TimelineJS-1.1/js/locale/pl.js
TimelineJS-1.1/js/locale/pt-br.js
TimelineJS-1.1/js/locale/pt.js
TimelineJS-1.1/js/locale/rm.js
TimelineJS-1.1/js/locale/ro.js
TimelineJS-1.1/js/locale/ru.js
TimelineJS-1.1/js/locale/si.js
TimelineJS-1.1/js/locale/sk.js
TimelineJS-1.1/js/locale/sl.js
TimelineJS-1.1/js/locale/sr-cy.js
TimelineJS-1.1/js/locale/sr.js
TimelineJS-1.1/js/locale/sv.js
TimelineJS-1.1/js/locale/ta.js
TimelineJS-1.1/js/locale/te.js
TimelineJS-1.1/js/locale/th.js
TimelineJS-1.1/js/locale/tl.js
TimelineJS-1.1/js/locale/tr.js
TimelineJS-1.1/js/locale/uk.js
TimelineJS-1.1/js/locale/zh-cn.js
TimelineJS-1.1/js/locale/zh-tw.js
TimelineJS-1.1/js/timeline-min.js
```

I'll have to check how these files are loaded and whether the overrides would work for them, too.

**Comment by DegrangeM** [comment]
Lets help you a little:

- For EmbeddedJS : it's the unminified file, the minified file is the one getting loaded with preloadjs

- For branch scenario:
   file are not used as they are compiled into a unique js file that is generated, they probably forgot to exclude them from build

   https://github.com/h5p/h5p-branching-scenario/blob/master/webpack.config.js

   strangely your script missed libraryScreenOverlay.js ?

- For CKEditor:

   https://github.com/h5p/h5p-ckeditor/blob/37d6ae1389beacd7b68574cc1fc7d2f2ea3262b5/h5p-ckeditor.js#L163

   https://github.com/h5p/h5p-ckeditor/blob/37d6ae1389beacd7b68574cc1fc7d2f2ea3262b5/h5p-ckeditor.js#L97

   element are then loaded by the ckeditor library (not related to h5p) using document.createElement

- For Odometer : The default theme is included in proloadCss, the other css file are alternative style that aren't used.

- For TimelineJS, it will not : 
https://github.com/h5p/timelinejs/blob/288d9533576f77bd790f4900df0214fc6a3899ba/timeline.js#L8

   The timelinejs library (not related to h5p) use this window.embed_path variable to load later the files with a script tag.

So the library that will probably not be loaded correctly are CkEditor and Timelinejs.

A solution could be to rewrite the some native function but this seems a little dirty ? Maybe use dom mutator watcher but this might be bad for performence ?

**Comment by DegrangeM** [comment]
Here a working solution:

```javascript
nativeSetAttribute = HTMLScriptElement.prototype.setAttribute;
HTMLScriptElement.prototype.setAttribute = function (name, value) {
    if (name === 'src') {
        // replace src to data-uri if ressource exist
        // todo
        if (value === 'foo') {
            value = 'bar';
        }
    }
    nativeSetAttribute.call(this, name, value);
}
Object.defineProperty(HTMLScriptElement.prototype, 'src', { // also apply the modification if the src is set with the src property
    set(value) {
        this.setAttribute('src', value);
    }
});
```

a little dirty but will probably work for everything.

Same can be done for style.

**Comment by sr258** [comment]
Thank you for your extensive work! I'll try integrating the mutation observer!

**Comment by DegrangeM** [comment]
The provided solution is the one modifing native function. If you want to use the mutation observer instead, here some information : https://developer.mozilla.org/en/docs/Web/API/MutationObserver only watching direct child of head and body might be enough.

**Comment by sr258** [comment]
I'll go for your replacements of the setAttribute property. I think it should work fine. I've got it working for script and I'll add it for styles tomorrow.

**Comment by sr258** [comment]
I've created a PR and things seem to work fine: https://github.com/Lumieducation/H5P-Nodejs-library/pull/1362

The bundle grows to 2.4 MB for your content type, however. As all scripts are included in base64 the size grows in comparison to the regular file size.

I'd be happy about a review of the changes and then I'll merge them.

**Comment by DegrangeM** [comment]
I don't know if I did something wrong.

I switched to the branch, uploaded my library (from the h5p file I put as attachment earlier), launched `npm start`, went on the server, created a content type code highlighter and exported to html. However when I test it doesn't seems to work, the url is not replaced by the data uri. I don't know why it work for you and not for me.


[2514647987.html.txt](https://github.com/Lumieducation/Lumi/files/6403681/2514647987.html.txt)

The setAttribute is still the native one in this html file.

**Comment by sr258** [comment]
Did you run `npm run build` before running `npm start`?

**Comment by DegrangeM** [comment]
No, I will do that.

**Comment by DegrangeM** [comment]
Had to replace a line to `"build": "npx tsc && copy src\\*.js build",` because I am on windows.

I confirm it work for my content-type. (tried timeline content type but it doesn't work for this, I will search why)

**Comment by DegrangeM** [comment]
I found why it doesn't work for timeline and it's unrelated to our change.

It's because it do a ajax request at some time and it rejected because it's on file: protocol.

https://github.com/h5p/h5p-timeline/blob/78174f77dc5e330ef495f82823392821ce0be18a/timeline.js#L110

**Comment by DegrangeM** [comment]
Unless you also want to modify the native ajax function but this is probably very complicated :D 

edit : might not be complicated, doing some tests

**Comment by DegrangeM** [comment]
closing this issue
