### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by devaxel** [Lumieducation/Lumi#1688]
Hi.
Using latest LUMI on Windows 10.
I can't open a file previously saved in LUMI...just seeing the loading circle. No error is show...just the loading circke and norhing happens. Any idea whats wrong here?

**Comment by sr258** [comment]
Can you please upload the file or send it to c@lumi.education?

**Comment by sr258** [comment]
Closing the issue, as we didn't receive a file and can't investigate.
