### ISSUE TITLE
Export Option for H5P options

### ISSUE THREAD

**Issue by asexauer** [Lumieducation/Lumi#1795]
Exporting to HTML is a great feature. I'm missing to select typical H5P options to show or not show the embed code, reuse, license … in the usual bar below the h5p-content.
It would be great if this could be selected in the export dialog in future versions.
Workaround at the moment is to do it manually in the exported html.

**Comment by sr258** [comment]
Thank you for you suggestion! The license information is definitely something that needs to be added. I'm not so sure about whether the reuse and embed buttons would work properly if you export to HTML. The reuse button requires a .h5p file, which we don't have once you've exported to HTML. Generating the embed code might work, but I haven't looked at the way this is done in H5P, so I can't promise this will work for generic .html files without a server backend.

**Comment by asexauer** [comment]
Thank you, I missed that part. I tested it, without the server component, embed and reuse is not functional.
An embed code could maybe generated with some javascript parsing the actual location, when the user clicks on the option for reuse during export, the h5p-file could be saved in the export directory additionally.
But I understand that this is extra work, and could live without. Thank you for your great work with the Lumi-editor.

**Comment by mz83ude** [comment]
"_The license information is definitely something that needs to be added._"

That would be great or even mandatory for OER!

Thanks for this great tool!

**Comment by sr258** [comment]
Implemented in 0.9.1.
