### ISSUE TITLE
couchdb-views are not created on setup in production-environment

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#185]

**Comment by budumlu** [comment]
Gibt es eine Möglichkeit die Datenbank manuell zu initialisieren?

**Comment by JPSchellenberg** [comment]
Im Prinzip ja. Die Datenbank (couchdb) und hat ein eigenes Web-Interface: http://<ip des pi>:5984/_utils 
Bei jedem Neustart von Lumi sollte überprüft werden ob alle Couchdb-Views (http://guide.couchdb.org/editions/1/de/views.html) aktuell sind und gegebenenfalls sollte die Views aktualisiert werden. Das funktioniert noch nicht. Die Views sind hier abgespeichert:
https://github.com/Lumi-education/Lumi/blob/master/src/server/db/setup/couchdb/views.ts
