### ISSUE TITLE
Interactive video stuck on "Video player laoding..." on Chrome 94

### ISSUE THREAD

**Issue by antonvalletas** [Lumieducation/Lumi#1866]
**Describe the bug**
An interactive youtube video is not rendered when using Chrome 94 but works when using Firefox latest version. 

**Environment (please complete the following information):**
 - OS: Both Linux and Windows on Chrome 94
 -  - Lumi Version: latest

**To Reproduce**

Create an interactive video quizz, export as single HTML, open it on Chrome, and video player is stuck on "Video player loading...". Works correctly on non-chromium browsers such as Firefox

**Expected behavior**
Video quizz should work on Chrome based browsers as well as Firefox. 

**Screenshots**
![Screenshot from 2021-09-25 19-54-01](https://user-images.githubusercontent.com/32290669/134781435-2136fe05-ac29-47b1-b3ff-81a4c267ff03.png)
![Screenshot from 2021-09-25 19-53-47](https://user-images.githubusercontent.com/32290669/134781436-c6ea50f5-2006-47c3-ac55-beaef40d9696.png)
![Screenshot from 2021-09-25 19-50-47](https://user-images.githubusercontent.com/32290669/134781438-6bc4f468-fbc6-4365-9b59-1cebee65c819.png)

**Comment by sr258** [comment]
I think this is fixed in the latest beta: https://github.com/Lumieducation/Lumi/releases/tag/v0.8.2-beta.2 Please give it a try and report back.

**Comment by antonvalletas** [comment]
Yes, 0.8.2 fixes the issue.

**Comment by sr258** [comment]
Great. I‘ll try to release the beta into the mainstream release soon, as it looks stable. There’s only a minor issue with the language detection on first startup that must be resolved.
