### ISSUE TITLE
Certificate has expired on https://api.h5p.org/v1/sites 

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#1879]
**Describe the bug**
The Editor shows the following message:

![Screenshot 2021-10-01 at 14 46 55](https://user-images.githubusercontent.com/9697985/135621847-e088c92e-6bf6-4ec6-8de8-38a930bf9690.png)

It looks like the certificate on api.h5p.org has expired. Is there something we can do or is it a problem on h5p.org s side?

![Screenshot 2021-10-01 at 14 47 43](https://user-images.githubusercontent.com/9697985/135621936-dbb151b1-51a1-4584-aa48-abea436a749e.png)

**Comment by sr258** [comment]
Hmm, I just checked, the certificate is valid until November for me. There's nothing we can do about it, if it's not the machine time that's incorrect.

**Comment by sr258** [comment]
@JPSchellenberg there have been 0 requests on the Matomo server too since Thursday afternoon! Looks like a serious issue in the app.

**Comment by sr258** [comment]
See https://github.com/electron/electron/issues/31212
