### ISSUE TITLE
False positive with VirusTotal scan

### ISSUE THREAD

**Issue by nmarafo** [Lumieducation/Lumi#1952]
Virustotal detects a false positive with Lumi and maybe it could be related to the following Electron [issue](https://github.com/electron-userland/electron-builder/issues/5004)

![false_positive](https://user-images.githubusercontent.com/18734989/140044173-aa915b2c-290a-4083-b826-11390c917bd6.png)

**Comment by sr258** [comment]
Thanks a lot for reporting this. I believe this is the relevant issue: https://github.com/electron-userland/electron-builder/issues/6334 Looks like there must be an update electron-builder version to fix this...

**Comment by nmarafo** [comment]
The issue has been closed in electron-builder. Seems there is a solution.

**Comment by sr258** [comment]
Alright, the next build should not be affected then. I‘ve checked 0.8.3 some time ago and there was no false positive. Closing this issue. Thank you.
