### ISSUE TITLE
Table properties bug

### ISSUE THREAD

**Issue by AgnewNZ** [Lumieducation/Lumi#1996]
**Describe the bug**
Table borders and other properties (padding, width etc) don't display when using the Table content type in a Column or Interactive Book.

**Environment (please complete the following information):**
 - OS: Window 10 Pro, Version 21H2
 - Lumi Version 0.8.2.0

**To Reproduce**
When using Column or Interactive Book:
1. Click 'Add Content'
2. For 'Content' select 'Table'
3. In the 'Table' content box, right-click on the table text and select 'Table properties' from the dropdown menu (Screenshot1)
4. Make changes to the properties, e.g. 'Border size: 1; Cell spacing: 1; Cell padding: 5;' and click 'OK' (Screenshot2)
5. The table preview displays as expected (Screenshot3)
6. Click 'View'
7. See error (no borders, padding etc.) (Screenshot4)

**Expected behavior**
I would expect to have the selected border properties display.

**Screenshots**
Screenshot1:
![Screenshot1](https://user-images.githubusercontent.com/72720634/142797004-05e8fe09-efdc-41db-b2aa-f58a751a4314.jpg)
Screenshot2:
![Screenshot2](https://user-images.githubusercontent.com/72720634/142797043-3de128fb-a8b2-4b59-a2e4-9f36d4ea6bde.jpg)
Screenshot3:
![Screenshot3](https://user-images.githubusercontent.com/72720634/142797091-a52a98b7-4cf9-4c2a-b8c5-fd0bca07392a.jpg)
Screenshot4:
![Screenshot4](https://user-images.githubusercontent.com/72720634/142797107-db45cf00-acdb-4a9e-88e4-1bc393e93e10.jpg)

**Additional context**
Adding table properties works as expected when using H5P.com.

**Comment by sr258** [comment]
Thank you for your very detailed report! I suspect that the sanitization method we use removed the styles. I'll investigate and report back soon!

**Comment by sr258** [comment]
I've fixed the problem in our upstream h5p library. If tables are allowed, you can now set all the properties in the table dialogs (captions are places outside the table for some reason when you hit save; it looks like CKEditor is misconfigured by the h5p core; this is something we can't fix on our side). It's interesting that this works on h5p.com! I've tried this out with the Drupal 7 implementation and there the table properties are also lost on save. When I wrote the HTML sanitization code I followed the example of the open source h5p core, but it looks like the commercial core contains changes which are not in the open source version...

Expect a new Lumi release in the next few day, which will contain the bugfix.

**Comment by AgnewNZ** [comment]
Awesome! Thanks a lot :)

**Comment by sr258** [comment]
Resolved in 0.8.3, which was released today.
