### ISSUE TITLE
deployment support / system wide installation

### ISSUE THREAD

**Issue by Lukas-UAUX** [Lumieducation/Lumi#2132]
**Is your feature request related to a problem? Please describe.**
To be used in an bigger environments like at a university or other educational institutions (or companies for that matter) an app commonly should be deployable silently and administrative by means like SCCM, OPSI or sth. similar. An installer that runs and installs in user context will either fail or be unusable afterwards.  

**Describe the solution you'd like**
The app already offers an "/S" parameter for silent installation. An system-wide installation should be available either by being called with administrative rights or by another additional Flag "/ALLUSERS"

**Describe alternatives you've considered**
Installing it for every possible user (for example on login) is not really an option. Just keeping track of every installation and version (ege. for managed Updates) would be impossible

**Comment by Lukas-UAUX** [comment]
Also, user-based installations undermine the administrator of the institution...

**Comment by swirly** [comment]
I have to add that usually, user install is not possible because of disk space. In a k-12 school in France, we have commonly only 1Gb of storage for each pupil. If we have to install "per user" application in profiles, we just fill all storage space very quickly.

**Comment by sr258** [comment]
Working on this in a branch. The next beta release will include more installers.

**Comment by sr258** [comment]
0.9.1 now includes a system-wide installer.
