### ISSUE TITLE
Add correct simplified Chinese variant code for the h5p php editor library

### ISSUE THREAD

**Issue by samumist** [Lumieducation/Lumi#2143]
**Is your feature request related to a problem? Please describe.**
I'm a bit frustrated with the crazy landscape of how simplified Chinese of h5p (editor library, content types etc) was implemented across different platforms and apps, such as WordPress, Moodle, Drupal and Lumi app.

Having tested on all the platforms and I can verify the implementation of simplified Chinese language on different platforms and apps as shown in the following table.

<img width="706" alt="截屏2022-02-18 11 00 53" src="https://user-images.githubusercontent.com/3883086/154609487-5c38b2de-c979-46e9-becd-b24023d0265e.png">

From the table above we can see that Lumi implements the `zh` as the simplified Chinese translation. The implementation is consistent across the `locales` translation (almost complete, but the `client` still only has `zh-cn` variant ), but not for the `h5p/editor/` library, which also only has the `zh-cn` variant which lumi didn't pick up (see screenshots below).
 
<img width="1000" alt="截屏2022-02-18 11 14 45" src="https://user-images.githubusercontent.com/3883086/154611096-cfed7607-2eb7-498b-81e4-1c3e75aae6d5.png">

And there's no language fallback mechanism implemented and it would be very difficult to convince all the platforms to implement such a fallback mechanism or use a single standard language code.

**Describe the solution you'd like**
The simplest solution would be to provide all three language variant translation (with identical content) `zh`, `zh-cn` and `zh-hans` to all the libraries.

I've sent in a H5P editor  php library [PR](https://github.com/h5p/h5p-editor-php-library/pull/141) with the latest translation but not sure when or whether it will get accepted. 

I can send in a PR directly to this repo and hopefully get it included in the next 0.9 release.

Thanks,
Sam

**Comment by sr258** [comment]
Hi Sam,

I know about the mess with the Chinese language variants in H5P. I don't think that duplicating the files with the same content is a good idea in the long run as it will inevitably lead to inconsistencies if future translators don't understand that they have to modify all three files at once. I'll check if I can implement a fallback mechanism in Lumi that can one of the three files if the user has chosen simplified Chinese.

**Comment by samumist** [comment]
Hi Sebastian,

Yes, you're absolutely right that in the long run it would be a nightmare to maintain all three variants, giving that there are so many libraries to maintain. And It took me a while to figure out which variant shows correctly on which platform. It would be very confusing for new translators.

Thanks for considering to implement a fallback mechanism for Lumi. 

Maybe we could implement this in two steps:
### Step 1: add the `zh` translation
By adding the `zh` language of the H5P Editor library, we can 1) make it consistent with the rest of the simplified Chinese translation in Lumi and 2) have the correct editor interface without a fallback mechanism in place.

### Step 2: implement the fallback mechanism in Lumi

**Comment by sr258** [comment]
I've done all of that in the core library (h5p-nodejs-library). I'll push a release of the it once all tests in the CI pipeline have succeded. I then need to reference the new core in Lumi and publish a new release. It will be a beta release of 0.9 at the moment, as I still want to test some changes in Lumi before publishing the final release of 0.9.

**Comment by samumist** [comment]
That's great! 
Looking forward to the new 0.9 beta release!

**Comment by sr258** [comment]
@samumist I think it would make sense if you renamed all the various files into 'zh.json' for all simplified Chinese files in all repositories. Then there would be a consistent behavior in all platforms. Lumi should work fine now (release is in the CI pipeline) except for a minor issue: depending on the name of the variant file in the main content type library the language selector for the string translations at the bottom of the editor will default to 'Afrikaans' (first entry) if it's not 'zh.json'. The strings should still display correctly, though.

**Comment by sr258** [comment]
@samumist The new release is out: https://github.com/Lumieducation/Lumi/releases/tag/v0.9.0-beta.3

**Comment by samumist** [comment]
@sr258 
Yes, I can verify that the app interface looks correct with the new release. 
<img width="983" alt="截屏2022-02-18 18 20 27" src="https://user-images.githubusercontent.com/3883086/154663942-3bc2a13c-1d4f-4a53-9e15-22e4cfa9a63d.png">.

The h5p editor library seems not having the latest translation. I hope Lumi will implement it once it is accepted by the h5p official editor repo.

**Comment by sr258** [comment]
Yes, the translations are not updated in the editor. Can you notify me if the PR in the upstream repo is merged so I can update Lumi?

I've already tried updating to the latest editor code in a separate PR, but there seem to be some strange issues with library loading. This needs to be fixed before I can change the referenec of the editor core to the latest version...

**Comment by samumist** [comment]
> I think it would make sense if you renamed all the various files into 'zh.json' for all simplified Chinese files in all repositories.

@sr258 
Yes, this makes sense.
But what's the best way to approach this?  rename them on https://translate-h5p.tk/ ?

and with `zh`, we would cover both Lumi and WordPress. But what about Moodle (zh-cn) and Drupal (zh-hans)? shall I contact the maintainer to request the fallback implementation?

**Comment by samumist** [comment]
> Yes, the translations are not updated in the editor. Can you notify me if the PR in the upstream repo is merged so I can update Lumi?

Yes, I will.

**Comment by sr258** [comment]
> > I think it would make sense if you renamed all the various files into 'zh.json' for all simplified Chinese files in all repositories.
> 
> @sr258 Yes, this makes sense. But what's the best way to approach this? rename them on https://translate-h5p.tk/ ?

Renaming on translate-h5p doesn't work I think (at least I don't know how to do it; if you have found a way, you can certainly do it with Weblate!). It would have to be done through manual PRs, I think.

> and with `zh`, we would cover both Lumi and WordPress. But what about Moodle (zh-cn) and Drupal (zh-hans)? shall I contact the maintainer to request the fallback implementation?

Yes, I think it would make much sense to have the fallback implementation there. Fallback from a regional variant to the "main" variant (zh-cn --> zh) is something that is not uncommon and should be supported. The best place for the fallback would be the h5p core library. It should be relatively simple to fall back to the non-regional variant.
