### ISSUE TITLE
It doesn't work in Windows 10

### ISSUE THREAD

**Issue by moyongqing** [Lumieducation/Lumi#2164]
**Describe the bug**
When I execute NPM run I to download the dependent package, I execute NPM start to run and report an error:
DEBUG=lumi:* LOG_ LEVEL=debug PORT=8080 ./ node_ modules/. bin/electron .

'DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Environment (please complete the following information):**
 - OS: windows

**To Reproduce**
1. npm run i success
2. npm run start

**Expected behavior**
I can run projects on Windows 10 systems

**Comment by sr258** [comment]
@moyongqing I've pushed a new package.json version that now uses cross-env to set the environment variables. It should also work on Windows. Please pull the master branch, run `npm install` / `npm ci` again and then `npm start`.

**Comment by moyongqing** [comment]
> @moyongqing I've pushed a new package.json version that now uses cross-env to set the environment variables. It should also work on Windows. Please pull the master branch, run `npm install` / `npm ci` again and then `npm start`.

I run npm install as you say, and then npm start."build/server/main.js cannot be found" error message appears.it run successfully when I run  npm build and npm start.but as soon as the app comes in, the error page is displayed, with a prompt: cannot get/.

**Comment by sr258** [comment]
Uh, I forgot: You also have to run `npm run build` so that everything is transpiled. Also make sure that you install all dependencies for the client, too: run `npm run ci:all` for that.

**Comment by moyongqing** [comment]
I did thisand the app runs successfully, but the page is blank.And I wonder if I can use your h5p library on Vue web page?

**Comment by sr258** [comment]
Did you run `npm start` or `npm run start:dev`. The behavior is normal for the later. You should just run `npm start`.

**Comment by sr258** [comment]
In general, you can use the library on vue, but you should use the generic html webcomponent then. (https://docs.lumi.education/npm-packages/h5p-webcomponents)

**Comment by moyongqing** [comment]
I've tried.

**Comment by moyongqing** [comment]
> In general, you can use the library on vue, but you should use the generic html webcomponent then. (https://docs.lumi.education/npm-packages/h5p-webcomponents)

Can I use a PHP server instead of node server？

**Comment by sr258** [comment]
Not with our tech, no - our system is completely built around NodeJS. You'll have to use the official implementations (https://github.com/h5p/h5p-editor-php-library, https://github.com/h5p/h5p-php-library) if you want to use PHP.
