### ISSUE TITLE
Edit an uncompressed h5p file directly

### ISSUE THREAD

**Issue by philschatz** [Lumieducation/Lumi#2265]
:wave: Hello and thanks for a great desktop editor!

**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to open a directory containing an uncompressed h5p file.

**Describe the solution you'd like**
I would like to be able to edit an uncompressed h5p file, not just a compressed h5p file.

**Describe alternatives you've considered**
Creating a script for non-technical users that zips the directory into an h5p file, opens Lumi, and then unzips the h5p file again when lumi closes.

Unfortunately, this is difficult for non-technical users to use.

**Additional context**
I would like to use an h5p editor to add interactive content to [open textbooks](https://github.com/openstax).

**Comment by sr258** [comment]
Hi,

can you describe your use case a bit more closely? The issue I see here is that the uncompressed files also include libraries and Lumi has a central library storage system. For this reason it will be pretty difficult to implement this.

**Comment by philschatz** [comment]
Thanks @sr258 !

We would like to store the unzipped h5p files in git and use the Lumi editor to edit them.

## Background

We do not use h5p currently so here is an example of something similar that we do:

1. [Here](https://openstax.github.io/osbooks-writing-guide/media/Interactive/090221_opx_comp_ch02_drag_and_1c_drop_matching/) is a rendered version of an Interactive (think "Activity")
2. The data for the Activity (think `content.json`) is currently stored in [this XML file](https://github.com/openstax/osbooks-writing-guide/blob/main/media/Interactive/090221_opx_comp_ch02_drag_and_1c_drop_matching/data/data.xml)
3. If authors clone this repository the `content.json` and asset files would be in the filesystem rather than in an h5p/zip file

## Proposal

I think that both the compressed and uncompressed files have the same files you mentioned (the included libraries).

If the example above was replaced with an unzipped h5p file ([and some magic](https://www.npmjs.com/package/h5p-standalone)) then our authors would be able to use the Lumi editor and these Activities could be rendered in our books as iframes.

## V2

If that works then we would like to remove duplicated library files in the git repository by only storing the content.json and assets. That would reduce the amount of autogenerated content in the repo and would allow us to customize the CSS & JS of these activities.

I hope this helps

**Comment by sr258** [comment]
Hi, I see what you're trying to achieve. Unfortunately @JPSchellenberg and me are very busy at the moment and have little time to spend on our open source projects. This feature would benefit too few people, so we can't focus on it at the moment. I would accept a contribution adding this mode, but I can't develop it at the moment, I'm afraid.

**Comment by philschatz** [comment]
Ok thanks for the update and being willing to accept a contribution if we submit a Pull Request
