### ISSUE TITLE
Lumi crashes when i click ( create new H5P) , OS: windows10, Lumi version 0.9.1, steps: go to H5P editor then click on (create new H5P) the app closes

### ISSUE THREAD

**Issue by mrezzov** [Lumieducation/Lumi#2275]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]
 - Lumi Version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sr258** [comment]
@mrezzov Thank you for your report. I was quite busy, so I didn't have the time for an investigation into this bug. Please install the latest beta version by downloading it from https://github.com/Lumieducation/Lumi/releases/download/v0.9.2-beta.2/Lumi-Setup-0.9.2-beta.2.exe and installing it. (If you use the Windows Store version, please uninstall it first) I hope the bug will disappear. Please report back.

**Comment by Anki1978** [comment]
I had the same issue, that Lumi crashed when trying to open a file. Now with the link of your beta version it seems to work properly. Thank you so much.
