### ISSUE TITLE
H5P Interactive video does not load (SOLVED)

### ISSUE THREAD

**Issue by remcoNL** [Lumieducation/Lumi#2284]
![image](https://user-images.githubusercontent.com/19585042/171143628-2b95761a-05ed-4c85-83c3-d53367b37f5a.png)

**Describe the bug**
Some of the H5P content works fine in the Lumi editor, but 'interactive video' cannot be loaded. 

Quiz, Fill in the blanks and Drag the Words do work, but Course Presentation gives the same error.

**Environment (please complete the following information):**
I've tried on Mac OS Montery and Windows10, 

**To Reproduce**
Select 'net H5P' and click 'Interactive video'

** Extra info **
I also installed Lumi 8.1 from an earlier download, which gives the same problem. So I think the software might be ok, but it has to do with some settings somewhere...?

**Comment by remcoNL** [comment]
When I installed H5P on my Moodle site and tried the Interactive Video it had an error message:

`Missing required library H5PEditor.ColorSelector 1.3`


On the [H5P forum](https://h5p.org/node/1191351) I found this solution and it worked for me:

_Force the ColorSelector library (1.2.6) to update by importing a new content type that isn't already installed. I used Image Hotspots._

**Comment by sr258** [comment]
Thanks for the report and the solution!
