### ISSUE TITLE
Outdated dependencies and lock file issues

### ISSUE THREAD

**Issue by sr258** [Lumieducation/Lumi#344]
Not all dependencies in package.json are updated by Renovate. Several are currently outdated, even though they are not major releases. @JPSchellenberg , I can update them manually, but I'd like to check with you whether they are pinned on purpose. 

I also have had trouble running `npm ci`: Weirdly, there is always some file missing in node_modules after it. I want to regenerate package-lock.json for this purpose. Any concerns?

**Comment by sr258** [comment]
There is also another problem with running `npm ci` on windows, even if I regenerate the package-lock file and clean my npm cache: I get the error described [here](https://github.com/fsevents/fsevents/issues/301). It's a weird issue with npm and fsevents on Windows. `npm ci` won't work there for some time, until all packages have updated fsEvents or npm ignores the package (it's only needed for mac and shouldn't be used in Windows at all).

**Comment by JPSchellenberg** [comment]
> Not all dependencies in package.json are updated by Renovate. Several are currently outdated, even though they are not major releases. @JPSchellenberg , I can update them manually, but I'd like to check with you whether they are pinned on purpose.
> 
> I also have had trouble running `npm ci`: Weirdly, there is always some file missing in node_modules after it. I want to regenerate package-lock.json for this purpose. Any concerns?

That might be, because I closed some pull-requests, because my development-environment was broken and I could not find the culprit. We should update them manually and regenerate the package-lock.json.

(I regenerated the package-lock.json a lot of times, because something was broken)
