### ISSUE TITLE
Linux version behind macOS and Windows

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#385]
**Describe the bug**
The Linux version is behind the macOS and Windows version. This is due to the fact that for a release `semantic-release` is run on the CI-Server for Windows and macOS. During the process, `semantic-release` checks the latest version, increments the number and writes it to the `package.json` and pushes it back to github. Then another Ubuntu-Environment is started where the Linux version is built. `semantic-release` is run here too, but the branch is out-dated because `semantic-release` pushed the updated `package.json` to github, therefore no release is created and the `package.json` for Linux is not updated. 

**Environment (please complete the following information):**
 - CI

**Possible solution**

We could try to make `package.json` an artifact that is carried over to the ubuntu-environment. That way the version should already be updated.

**Comment by sr258** [comment]
Carrying over `package.json` will only work if we disable the semantic-release step altogether in the ubuntu environment. Otherwise "The local branch master is behind the remote one, therefore a new version won't be published." will still apply.

**Comment by sr258** [comment]
Do you know at what point semantic-release pushes its changes to `package.json` to the repo? I would have thought that the whole linux job is run after the first job is fully finished and then it should checkout the current revision. 

We could also try to add something like `- run: git pull` to checkout the current revision.

**Comment by sr258** [comment]
Another alternative might be to have our own action for the semantic-release part. It does its checks and creates the release. Then we have another action that triggers on the `release` event. It then creates the distribution packages in the two jobs (which don't contain semantic release anymore)

**Comment by JPSchellenberg** [comment]
> Another alternative might be to have our own action for the semantic-release part. It does its checks and creates the release. Then we have another action that triggers on the `release` event. It then creates the distribution packages in the two jobs (which don't contain semantic release anymore)

I tried that one as it seemed the best solution, but GitHub Actions can not trigger GitHub Actions to prevent loops. So a GitHub Action can not trigger the release-event.



> Do you know at what point semantic-release pushes its changes to `package.json` to the repo? I would have thought that the whole linux job is run after the first job is fully finished and then it should checkout the current revision.
> 
> We could also try to add something like `- run: git pull` to checkout the current revision.

It pushes the package.json in the [release step](https://github.com/Lumieducation/Lumi/blob/master/release.config.js#L7)

I think the problem is, that the action checks out at the specific commit.
`- run: git pull` could work, but from the GitHub Action docs it sounds like the best-practice way would be to carry the package.json over via artifacts, because those are replaced after the `git checkout`.
