### ISSUE TITLE
Mathematical expressions in H5Ps

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/Lumi#410]
**Is your feature request related to a problem? Please describe.**
Lumi does not display mathematical expressions in LaTeX.

**Describe the solution you'd like**
Lumi should be able to display mathematical expressions.

According to https://h5p.org/mathematical-expressions we have to install the following library:
https://h5p.org/sites/default/files/h5p-math-display-1.0.5.h5p

I think @sr258 also had the idea of a library-management-section where the user can manage all libraries. That would be an ideal use case or we include that library right from the beginning.

**Comment by sr258** [comment]
I believe this requires more work:

There is some syntax in library.json which is unknown to me:
```
 "addTo": {
    "content": {
      "types": [
        {
          "text": {
            "regex": "/\\$\\$.+\\$\\$|\\\\\\[.+\\\\\\]|\\\\\\(.+\\\\\\)/"
          }
        }
      ]
    }
  }
```

I assume, this means that the library is added to any content type with text fields automatically. This must be done in the server component then. I'll have to check how the H5P server does this. (It is an interesting feature by the way, as it probably also allows to customize visuals and other behaviour through addons).

We also have to bear in mind that other system that don't have the library installed might not be able to display the formula.

Last, the library doesn't include MathJax but loads it from an online server. If we want true offline behaviour, we'd have to include the relevant files in the library.

**Comment by sr258** [comment]
These are the mysterious "addons" that were sometimes mentioned in the core. E.g. see `h5p.classes.php: 2174` in h5p-php-library. It's a (rather unexpected) side effect of H5PContentValidator. Addons currently only seem to work for textfield regexes, though.

**Comment by JPSchellenberg** [comment]
It is one of the most requested features. A band-aid solution could be to include the MathJax-script in the renderer. It worked on Lumi.run: https://github.com/Lumieducation/Run/blob/master/src/server/h5p/Player.renderer.ts#L20

but I am not sure which side-effects we are getting.

**Comment by sr258** [comment]
Adding MathJax to the Electron app will certainly work, but when you upload the package to a system where MathJax isn't enabled, the formulas still won't show.

**Comment by sr258** [comment]
h5p-nodejs-library now supports addon, so we can use H5P.MathDisplay in the future.

**Comment by sr258** [comment]
Next step to do this would be to include H5P.MathDisplay when Lumi is installed and to enable it in the configuration.

**Comment by apienk** [comment]
What's the status of this feature? Unfortunately, the lack of Latex support in Lumi is a show stopper for us. We're developing a lot of H5P content, 90% being STEM, so MathDisplay library with a Latex chemistry extension is a must. Currently, the development runs on Wordpress, which is not offline-safe. We would love to be able to use Lumi instead.

**Comment by sr258** [comment]
How do you plan to distribute the content? Do you want to use the html exporter or save h5p packages?

**Comment by apienk** [comment]
> How do you plan to distribute the content? Do you want to use the html exporter or save h5p packages?

For now, we'd use Lumi to create content offline, save as .hp5, then import it into our Wordpress site. But, in the future, we're interested in using the exporter (and reporter) as well. Great job with Lumi!

**Comment by apienk** [comment]
Actually, I've just found an easy workaround. It's enough to just import any H5P resource which already contains H5P.MathDisplay library, and you're good. The editor now renders Latex with MathJax in new resources as well! In order to add support for custom Latex extensions (one for chemical notation, in our case), just edit the mathdisplay.js file in the libraries folder.

**Comment by davidjabon** [comment]
Just a comment. I have found putting the H5P.MathDisplay library in the libraries folder is sufficient for the math display to work in Lumi and even produce free standing html exports that display the math correctly. So Sebastian's suggestion to (eventually) "include H5P.MathDisplay when Lumi is installed and to enable it in the configuration" would work perfectly; the configuration setting could simply move the library in or out. Meanwhile, manually adding the library is a simple workaround. On Windows the libraries are located in  users/username/AppData/Roaming/lumi/libraries.

However, default should be to include the MathDisplay. It is extremely rare that MathDisplay conflicts with anything.   H5P.org has MathDisplay enabled as well.

Super work here!

**Comment by DegrangeM** [comment]
Thanks @davidjabon it worked perfectly. Would be nice if mathdisplay was included by default though.

**Comment by sr258** [comment]
We now support manual library uploads, so you can upload H5P.MathDisplay to get latex.

**Comment by sokunthearithmakara** [comment]
Is there a way to make math expressions rendered on Course Presentation during editing?

**Comment by sr258** [comment]
@sokunthearithmakara Do you mean in the text editor or inside the WYSIWYG editor of Course Presentation? Maths should be rendered correctly in the WYSIWYG editor if you download the MathJax extension from [https://h5p.org/mathematical-expressions](https://h5p.org/mathematical-expressions) and upload it in Lumi's library management area.

**Comment by sokunthearithmakara** [comment]
@sr258 I did install the H5P.MathDisplay library. On Lumi, the math expressions are rendered correctly only when the course presentation is in the View mode. On WordPress H5P editor, the math expressions are rendered as soon as they are added to the slides (using any content types) even on Edit mode.
See attached screenshots.
![Lumi Math Expression](https://user-images.githubusercontent.com/16877863/116967528-aff84c80-acdc-11eb-837f-03b8b894d9b0.png)
![H5P Math Expression](https://user-images.githubusercontent.com/16877863/116967531-b1297980-acdc-11eb-9fa9-abb86aeb2bae.png)

**Comment by sr258** [comment]
Alright, I can reproduce the error here. I'll investigate.
