### ISSUE TITLE
Missing images in H5P Dialog Cards created with Lumi

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#457]
An added (optional) image to a Dialog card is displayed only in the editor, but not in view mode. In the source code of the content.json you can see that the width and height information for the image is missing. If I add them manually in code, the image will be displayed. 

<img width="865" alt="Bildschirmfoto 2020-05-05 um 13 06 29" src="https://user-images.githubusercontent.com/58503/81059729-5397fc80-8ed1-11ea-9c35-c8da42caab34.png">

**Environment**
 - macOS 10.15.4
 - Lumi 0.27

**Broken:**

```json
  "dialogs": [{
    "tips": {},
    "image": {
      "path": "images/planung-9DG-IFl5p.jpg",
      "mime": "image/jpeg",
```

**Fixed:**

```json
  "dialogs": [{
    "tips": {},
    "image": {
      "path": "images/planung-9DG-IFl5p.jpg",
      "mime": "image/jpeg",
      "width": 1920,
      "height": 1280,
```

**Comment by sr258** [comment]
There already is a corresponding issue here: https://github.com/Lumieducation/H5P-Nodejs-library/issues/425
