### ISSUE TITLE
Add export option for H5P Standalone

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#458]
Using H5P-content still requires a server component. [H5P Standalone](https://github.com/tunapanda/h5p-standalone) provides the missing libraries to make H5P self-contained and run without an explicit server. It would be convenient if Lumi provided an export option for this. Technically this would only mean adding certain static files, see our [H5P-Creator](https://tools.vcrp.de/h5p_creator)). But maybe such a feature would interfere with Lumi.run (no offence intended)?

**Comment by JPSchellenberg** [comment]
As far as I understand [H5P Standalone](https://github.com/tunapanda/h5p-standalone) allows you to render H5P on an HTML-Page without the server-side. How would it look like to export it as a file? Do you mean that the H5P is being exported as a .html file?

**Comment by pheraph** [comment]
I have seen "solutions" that pack all files base64-encoded into a huge single HTML-file, which of course takes on absurd traits with large media files. I would find it perfectly sufficient and useful if Lumi could export a single zip-file with the standalone libraries added:

<img width="482" alt="Bildschirmfoto 2020-05-05 um 14 42 31" src="https://user-images.githubusercontent.com/58503/81067592-2e11ef80-8edf-11ea-920d-c5a28805f734.png">

This file can be placed and extracted anywhere to display the content.

**Comment by JPSchellenberg** [comment]
Well, that is no problem, as the `.h5p` files currently exported are just `.zip` files, but with a `.h5p`-extension. You can try it by changing the extension from `.h5p` to `.zip` and see that all libraries are included with the content-folder and the h5p.json. So for this export, we would only have to give the option to export it as `.h5p` or `.zip`. We also could generate an `index.html` to view the content. Would that be sufficient?

**Comment by sr258** [comment]
I've thought about this feature some time ago and it should be no problem to create an exporter for this, in general. It would make sense to provide a way of exporting H5P packages in a way that doesn't require a LMS. 

I've started working on a similar things two weeks ago, but was distracted by the S3 and Mongo backend for content storage: exporting to a single HTML file with inline resources. There is a branch of h5p-nodejs-library, in which I have some unfinished work on this:
https://github.com/Lumieducation/H5P-Nodejs-library/tree/try/save-html

**Comment by pheraph** [comment]
I am personally not committed to specifically integrating H5P Standalone. The project had its problems in the past, because it was orphaned at times and there were breaks to current versions of content types, so new versions were no longer compatible with it. Currently I am not aware of any problems, but of course it could happen again. In this respect a native solution of Lumi had its benefits, if this improved the sustainability (this is still a question to the project itself, if it has to be monetized or what the future of the project should look like...). 

From the user's point of view I can understand the single file appeal, but from a technical point of view I see the disadvantage that there is redundancy in the libraries, so content types cannot be cached across. It would be nice if exported HTML files could share libraries and take advantage of the browser caching and not load the already locally available libraries. That would speak for me rather for a multi-file approach?

**Comment by sr258** [comment]
I think we could easily have a multi-file HTML export that doesn't require the h5p standalone runtime, as h5p-nodejs-library is far more advanced than it. I'll work on this after I've done the S3/Mongo backend and a bug when uploading images.

**Comment by sr258** [comment]
The new version (yet to be released) has a feature that creates single file HTML packages out of h5p content. Does this satisfy your needs, @pheraph ?

**Comment by pheraph** [comment]
Thanks for the update! All resources and libraries would then be coded inline in a single HTML document, right? I'm still not sure if this makes sense technologically or performance-wise when I imagine a 100 MB HTML file with an MP4 encoded in it. On the user side, it certainly produces fewer errors because you only have to deal with one file and not path information and trillion files. Maybe an intermediate solution would be not to put the content resources into the HTML file and only the collected H5P libraries? If the single file solution is already implemented, I would like to get a picture of it. Would that be possible?

**Comment by sr258** [comment]
Lumi currently indeed produces is a 100 MB HTML file if you put a big MP4 into it. The underlying library also supports the intermediate solution in which there is a single HTML package for scripts and styles but all resources are kept separately.

You can check out these samples (you have to rename them to .html, as GitHub doesn't allow html file uploads):
[Image juxta.txt](https://github.com/Lumieducation/Lumi/files/5770304/Image.juxta.txt)
[blanks.txt](https://github.com/Lumieducation/Lumi/files/5770302/blanks.txt)

**Comment by pheraph** [comment]
I tested the image example with our LMS and learned the LMS has a limit for the size of a HTML file. We might increase it, but the more I think about it I'd love an option for the intermediate solution. Optimally everything nicely packed in a ZIP file, so that you can unpack the archive on the server side and everything just works without paying attention to path hierarchies (that would be something of the charm that the single file variant undeniably has). It would also have the advantage that you could easily exchange (replace) resources in the export version without having to go through H5P and Lumi again.

**Comment by sr258** [comment]
Alright, a zip package would be easy. I‘ll try this out. Won‘t you run into the same file size issues, though?

**Comment by pheraph** [comment]
Sounds good. The size limit only applies to HTML files and is not a general file size limit. I suspect it is due to potential performance issues of the WYSIWYG editor with large HTML content.

**Comment by sr258** [comment]
What size limit are we talking about? The HTML bundles will still be about 500 KB in size as they include all H5P core scripts, styles and library scripts and styles.

**Comment by pheraph** [comment]
Thanks for asking, that's totally fine. The current limit is 1MB, which might be increased if necessary, but not on a scale that would be required for inline ressources.

**Comment by joee1989** [comment]
A zip package solution would be great.  If you have a 360° tour with many images, you currently produce a huge HTML file with long loading times. Many many thanks in advance

**Comment by LyesJeu** [comment]
> Using H5P-content still requires a server component. [H5P Standalone](https://github.com/tunapanda/h5p-standalone) provides the missing libraries to make H5P self-contained and run without an explicit server. It would be convenient if Lumi provided an export option for this. Technically this would only mean adding certain static files, see our [H5P-Creator](https://tools.vcrp.de/h5p_creator)). But maybe such a feature would interfere with Lumi.run (no offence intended)?

Hi, how i can get your solution?
