### ISSUE TITLE
Broken symlinks in macOS zip file release

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#459]
If Lumi is installed on macOS (10.15.4) via the zip file from the releases page, Lumi cannot be started afterwards. At first glance this seems to be due to broken symlinks. In the Apple Disk Image the symlinks are intact and the installation works over there. I stumbled over it because the website doesn't always link the latest release, so I had loaded the broken zip file by mistake.

<img width="555" alt="Bildschirmfoto 2020-05-05 um 14 28 36" src="https://user-images.githubusercontent.com/58503/81066014-bba01000-8edc-11ea-81a2-e8ee6ba410ca.png">

**Comment by JPSchellenberg** [comment]
As far as I know, the .zip files are for the auto-updater. For macOS you should download the .dmg file and mount it. I will try to keep the homepage up to date with the latest release.
