### ISSUE TITLE
Appimage in release

### ISSUE THREAD

**Issue by cyberorg** [Lumieducation/Lumi#600]
Please include AppImage file in the release and get it listed on https://appimage.github.io/

Once AppImage is available in released files, see: https://github.com/AppImage/appimage.github.io#how-to-submit-appimages-to-the-catalog

Create a pull request with one file, like this example: https://github.com/AppImage/appimage.github.io/blob/master/data/AKASHA

This will make Lumi available to all Linux distributions easily.

Thanks

**Comment by sr258** [comment]
AppImages are currently not included because the build pipeline for Linux is lagging behind the macOS and Windows build: https://github.com/Lumieducation/Lumi/issues/385

PRs to fix it are welcome.

**Comment by sr258** [comment]
The AppImages seem to be built correctly now and they also work in Ubuntu 2004. I'm not sure, whether the Lumi AppImage currently meets all the requirements listed in [here](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage) and I'm not really well versed in Linux. @cyberorg could you confirm that the AppImage is ready to be submitted?

**Comment by cyberorg** [comment]
Thanks, tested on Ubuntu 2004, 

[appdir-lint.sh](https://github.com/AppImage/pkg2appimage/blob/master/appdir-lint.sh) gives the following warning, may be you can include that file as well. 

```
WARNING: No appdata file present. Please provide one in the AppImage as per the instructions on https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
Lint found no fatal issues
```
See "web-based form to quickly generate valid metainfo XML" on the link in WARNING.

I tried few appimages(openboard, bioanimation, sugarizer) didn't see that file in any of them, so I guess you can create PR for AppImageHub.

See also [including update information](https://docs.appimage.org/packaging-guide/optional/updates.html) in the appimage to make updating possible without having to download entire image again using zsync.

**Comment by sr258** [comment]
I've open a PR so that appimage.github.io can add Lumi. The auto-update is already working on my machine. Thanks for helping out here!

**Comment by cyberorg** [comment]
Awesome!
