### ISSUE TITLE
Lumi seems to be producing incomplete H5P-files in unknown constellations

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#615]
I have learned about a person who had problems installing and using Lumi on Windows. Firstly, Chrome showed the hint that the installer was a suspicious file, which understandably irritated the person:

![chrome](https://user-images.githubusercontent.com/58503/87559721-f2ec2380-c6ba-11ea-87e1-ab3fdd40446a.png)

After installation, the saved H5P file was reproducibly incomplete. As far as I can tell, the H5P libraries in particular are missing. I attached one of the files saved with Lumi (renamed from h5p to zip to bypass the attachment restriction):

[arithmeticquiz.zip](https://github.com/Lumieducation/Lumi/files/4925969/arithmeticquiz.zip)

So it contains only two files:

````
h5p.json
content/content.json
`````

Unfortunately I have no further information on the case, so I'm not sure if this is even suitable for further investigations. But at least it is documented as far as possible. Do you have an idea what this might be caused by?

**Comment by sr258** [comment]
Thank you for your reports!

About the first issue: This is sadly the case with all executables that are "new". Lumi isn't that widespread yet, so we get this warning. The only solution I see is to add Lumi to the Microsoft Store, which is on my mental TODO list.

About the second issue: I've reworked how libraries are included in the core library h5p-nodejs-library. This problem might be solved, once we've upgraded lumi to use the new core library.

**Comment by sr258** [comment]
I've checked whether the issue with the missing libraries in the packages still occurs: it looks like this was fixed by the upstream update of h5p-nodejs-library. I'll close this issue. @pheraph you can reopen it, if the issue persists in your setup.
