### ISSUE TITLE
Package validation failed - file size too large

### ISSUE THREAD

**Issue by pheraph** [Lumieducation/Lumi#617]
When trying to open a larger file (here: ~70MB), the error attached message file appears. Where is the upper limit and how can I increase it?  If you embed a video, this limit is quickly reached.

<img width="1000" alt="filesize" src="https://user-images.githubusercontent.com/58503/87711890-32446e00-c7a8-11ea-8e0d-ddeca5d9e503.png">

**Comment by sr258** [comment]
Thank you for your report. This should be easy to fix. Fix will follow soon

**Comment by sr258** [comment]
Should be fixed in next release. File limit is now 2 GB.

**Comment by pheraph** [comment]
Great, will test it.

BTW, remember to keep the webpage updated, last time I checked it didn't deliver the latest version.

**Comment by sr258** [comment]
The next release isn't out yet. @JPSchellenberg needs to re-sign the periodic contract update at Apple for the pipeline to succeed.

**Comment by JPSchellenberg** [comment]
I re-signed the contract and the build now works again.
